project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!DS2_preview_work/"
    - "!SQLcode/"
    - "!spring2024/"
    - "!quarto_presentations/"
    - "!AERapp/"
    - "!Ames_example/"
    - "!more_shiny/"
    - "!SQL_code/"
  resources:
    - "Data/*.csv"
    - "Data/"

website:
  title: "SDS 264: Data Science 2"
  navbar:
    background: primary
    search: true
    left:
      - file: index.qmd
        text: "Home"
      - file: syllabus_s26.qmd
        text: "Syllabus"
      - sidebar:tech_notes
      - sidebar:activities
      #- sidebar:projects
      - file: rtipoftheday.qmd
        text: "R Tip of the Day"

  sidebar:
    - id: tech_notes
      title: "Tech Notes"
      contents:
        - tech_setup.qmd
        - why_quarto.qmd
        - github_intro.qmd

    - id: activities
      title: "Activities"
      contents:
        - 01_review164.qmd
        - 02_strings_part1.qmd
        - 03_strings_part2.qmd
        - 04_strings_part3.qmd


  page-footer:
    left: |
      &copy; Joe Roith, 2026<br>
      All content licensed under ![](https://static.thenounproject.com/png/70967-200.png){height=20px} ([CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/))
    right: |
      Site built with [Quarto](https://quarto.org/)

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    code-overflow: wrap

editor: source
